# Generated by Django 5.0 on 2023-12-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.IntegerField(max_length=3),
        ),
    ]
